version: '3.9'
services:
  shipster-app:
    image: shipster-app
    container_name: shipster-app
    build:
      context: .
      target: development
    ports:
      - "8001:8001"
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      shipster-postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shipster-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
  shipster-postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    container_name: shipster-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
